{
  "formatVersion": "1.1",
  "component": {
    "group": "com.librity.checkpermission",
    "module": "checkpermission",
    "version": "4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ycsledqcqfajhgfirctn5bz5t4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "checkpermission-4.0.jar",
          "url": "checkpermission-4.0.jar",
          "size": 17967,
          "sha512": "01da8816d4690df6f056c180e36f4828b4a5600c76e86eb5e96427105ef5ad389c9792faf5e9d33e84010589dfcbc09f5c9a358edb4acddb6f77c8f15490a585",
          "sha256": "8d7a8572e576f9f0d3b87589d8f7b5dd970ecd511d41c53cef2829f2fe79a38b",
          "sha1": "103674eb49b0d6eaceabf355b7d218ac19580fe5",
          "md5": "ab0d4b9e9476f8f82d8d60d68520ef13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checkpermission-4.0.jar",
          "url": "checkpermission-4.0.jar",
          "size": 17967,
          "sha512": "01da8816d4690df6f056c180e36f4828b4a5600c76e86eb5e96427105ef5ad389c9792faf5e9d33e84010589dfcbc09f5c9a358edb4acddb6f77c8f15490a585",
          "sha256": "8d7a8572e576f9f0d3b87589d8f7b5dd970ecd511d41c53cef2829f2fe79a38b",
          "sha1": "103674eb49b0d6eaceabf355b7d218ac19580fe5",
          "md5": "ab0d4b9e9476f8f82d8d60d68520ef13"
        }
      ]
    }
  ]
}
